/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Socket(props) {
  const { nodes, materials } = useGLTF("./socket.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2 * 3, 0, 0]}
            position={ [ 1, 0, 0 ]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3d-model_1"].geometry}
          material={materials.skp_front_default}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3d-model_2"].geometry}
          material={materials["0129_WhiteSmoke"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./socket.glb");
